#!/bin/bash
# start all necessary tools for groundstation with fixedwing bomb drop

set -x
export ROS_IP=`hostname -I`
# connect to odroid on plane - IP address may need to change
export ROS_MASTER_URI=http://192.168.1.100:11311
# groundstation, bag, waypoint planner:
roslaunch launch/bombdrop_gs.launch


