#!/bin/bash
# start all necessary tools for groundstation with fixedwing bomb drop

set -x

# connect to odroid on plane - IP address may need to change
export ROS_MASTER_URI=http://192.168.1.100:11311
# groundstation, bag, waypoint planner:
roslaunch bombdrop_gs.launch


